//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     Source: liquid.txt
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Liquid.Ruby\writetest.rb
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Liquid.NET.Constants;
using NUnit.Framework;

namespace Liquid.NET.Tests.Ruby
{
    [TestFixture]
    public class LiquidTests {

        [Test]
        //[TestCase(@"{{ foo }}", @"{""foo"":""#<ThingWithToLiquid:0x00000002cc0ec8>""}", @"foobar")]
        [TestCase(@"{% if true %} {% elsif false %} {% else %} {% endif %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %} {% endfor %}{% if true %} {% endif %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %}	{% endfor %}{% if true %}	{% endif %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %}{% unless true %} {% endunless %}{% endfor %}{% if true %}{% unless true %} {% endunless %}{% endif %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %} {% capture foo %} whatever {% endcapture %} {% endfor %}{% if true %} {% capture foo %} whatever {% endcapture %} {% endif %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %} {% endfor %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %}{% cycle ' ', ' ' %}{% endfor %}{% if true %}{% cycle ' ', ' ' %}{% endif %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %} {% assign foo = 'bar' %} {% case foo %} {% when 'bar' %} {% when 'whatever' %} {% else %} {% endcase %} {% endfor %}{% if true %} {% assign foo = 'bar' %} {% case foo %} {% when 'bar' %} {% when 'whatever' %} {% else %} {% endcase %} {% endif %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %} {% assign foo = 'else' %} {% case foo %} {% when 'bar' %} {% when 'whatever' %} {% else %} {% endcase %} {% endfor %}{% if true %} {% assign foo = 'else' %} {% case foo %} {% when 'bar' %} {% when 'whatever' %} {% else %} {% endcase %} {% endif %}", @"{}", @"")]
        
        //[TestCase(@"{% for i in (1..10) %} {% assign foo = 'else' %} {% case foo %} {% when 'bar' %} {% when 'whatever' %} {% else %} x {% endcase %} {% endfor %}{% if true %} {% assign foo = 'else' %} {% case foo %} {% when 'bar' %} {% when 'whatever' %} {% else %} x {% endcase %} {% endif %}", @"{}", @"x     x     x     x     x     x     x     x     x     x     x")]
        [TestCase(@"{% for i in (1..10) %}{% for i in (1..10) %} {% endfor %}{% if true %} {% endif %}{% endfor %}{% if true %}{% for i in (1..10) %} {% endfor %}{% if true %} {% endif %}{% endif %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %}{% if true %} {% comment %} this is blank {% endcomment %} {% endif %}
      {% if true %} but this is not {% endif %}{% endfor %}{% if true %}{% if true %} {% comment %} this is blank {% endcomment %} {% endif %}
      {% if true %} but this is not {% endif %}{% endif %}", @"{}", @"but this is not 
       but this is not 
       but this is not 
       but this is not 
       but this is not 
       but this is not 
       but this is not 
       but this is not 
       but this is not 
       but this is not 
       but this is not")]
        [TestCase(@"{% for i in (1..10) %} {% assign foo = ""bar"" %} {% endfor %}{% if true %} {% assign foo = ""bar"" %} {% endif %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %}{% include 'foobar' %}{% endfor %}{% if true %}{% include 'foobar' %}{% endif %}", @"{}", @"foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar")]
        [TestCase(@"{% for i in (1..10) %}{% include ' foobar ' %}{% endfor %}{% if true %}{% include ' foobar ' %}{% endif %}", @"{}", @"foobar  foobar  foobar  foobar  foobar  foobar  foobar  foobar  foobar  foobar  foobar")]
        [TestCase(@"{% for i in (1..10) %} {% include ' ' %} {% endfor %}{% if true %} {% include ' ' %} {% endif %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %} {% if false %} this never happens, but still, this block is not blank {% endif %}{% endfor %}{% if true %} {% if false %} this never happens, but still, this block is not blank {% endif %}{% endif %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %} {% raw %} {% endraw %}{% endfor %}{% if true %} {% raw %} {% endraw %}{% endif %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %} {% comment %} whatever {% endcomment %} {% endfor %}{% if true %} {% comment %} whatever {% endcomment %} {% endif %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %}{% foobar %}{% endfor %}", @"{}", @"")]
        [TestCase(@"{% for i in (1..10) %}     x {% endfor %}{% if true %}     x {% endif %}", @"{}", @"x      x      x      x      x      x      x      x      x      x      x")]
        [TestCase(@"{% for i in (1..10) %}{% assign foo = 0 %} {% increment foo %} {% decrement foo %}{% endfor %}{% if true %}{% assign foo = 0 %} {% increment foo %} {% decrement foo %}{% endif %}", @"{}", @"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0")]
        [TestCase(@"{% if true and true %} YES {% endif %}", @"{}", @"YES")]
        [TestCase(@"{% if false and true %} YES {% endif %}", @"{}", @"")]
        [TestCase(@"{% if false and true %} YES {% endif %}", @"{}", @"")]
        [TestCase(@"{% if false %} this text should not go into the output {% endif %}", @"{}", @"")]
        [TestCase(@"{% if true %} this text should go into the output {% endif %}", @"{}", @"this text should go into the output")]
        [TestCase(@"{% if false %} you suck {% endif %} {% if true %} you rock {% endif %}?", @"{}", @"you rock ?")]
        [TestCase(@"{% if a or b %} YES {% endif %}", @"{""a"":true,""b"":true}", @"YES")]
        [TestCase(@"{% if a or b %} YES {% endif %}", @"{""a"":true,""b"":false}", @"YES")]
        [TestCase(@"{% if a or b %} YES {% endif %}", @"{""a"":false,""b"":true}", @"YES")]
        [TestCase(@"{% if a or b %} YES {% endif %}", @"{""a"":false,""b"":false}", @"")]
        [TestCase(@"{% if a or b or c %} YES {% endif %}", @"{""a"":false,""b"":false,""c"":true}", @"YES")]
        [TestCase(@"{% if a or b or c %} YES {% endif %}", @"{""a"":false,""b"":false,""c"":false}", @"")]
        [TestCase(@"{% if a or b and c %}true{% else %}false{% endif %}", @"{""a"":true,""b"":true,""c"":true}", @"true")]
        [TestCase(@"{% if a or b and c %}true{% else %}false{% endif %}", @"{""a"":true,""b"":true,""c"":false}", @"true")]
        [TestCase(@"{% if a or b and c %}true{% else %}false{% endif %}", @"{""a"":true,""b"":false,""c"":true}", @"true")]
        [TestCase(@"{% if a or b and c %}true{% else %}false{% endif %}", @"{""a"":true,""b"":false,""c"":false}", @"true")]
        [TestCase(@"{% if a or b and c %}true{% else %}false{% endif %}", @"{""a"":false,""b"":true,""c"":true}", @"true")]
        [TestCase(@"{% if a or b and c %}true{% else %}false{% endif %}", @"{""a"":false,""b"":true,""c"":false}", @"false")]
        [TestCase(@"{% if a or b and c %}true{% else %}false{% endif %}", @"{""a"":false,""b"":false,""c"":true}", @"false")]
        [TestCase(@"{% if a or b and c %}true{% else %}false{% endif %}", @"{""a"":false,""b"":false,""c"":false}", @"false")]
        [TestCase(@"{% if var %} NO {% endif %}", @"{""var"":false}", @"")]
        [TestCase(@"{% if var %} NO {% endif %}", @"{""var"":null}", @"")]
        [TestCase(@"{% if foo.bar %} NO {% endif %}", @"{""foo"":{""bar"":false}}", @"")]
        [TestCase(@"{% if foo.bar %} NO {% endif %}", @"{""foo"":{}}", @"")]
        [TestCase(@"{% if foo.bar %} NO {% endif %}", @"{""foo"":null}", @"")]
        [TestCase(@"{% if foo.bar %} NO {% endif %}", @"{""foo"":true}", @"")]
        [TestCase(@"{% if var %} YES {% endif %}", @"{""var"":""text""}", @"YES")]
        [TestCase(@"{% if var %} YES {% endif %}", @"{""var"":true}", @"YES")]
        [TestCase(@"{% if var %} YES {% endif %}", @"{""var"":1}", @"YES")]
        [TestCase(@"{% if var %} YES {% endif %}", @"{""var"":{}}", @"YES")]
        [TestCase(@"{% if var %} YES {% endif %}", @"{""var"":[]}", @"YES")]
        [TestCase(@"{% if ""foo"" %} YES {% endif %}", @"{}", @"YES")]
        [TestCase(@"{% if foo.bar %} YES {% endif %}", @"{""foo"":{""bar"":true}}", @"YES")]
        [TestCase(@"{% if foo.bar %} YES {% endif %}", @"{""foo"":{""bar"":""text""}}", @"YES")]
        [TestCase(@"{% if foo.bar %} YES {% endif %}", @"{""foo"":{""bar"":1}}", @"YES")]
        [TestCase(@"{% if foo.bar %} YES {% endif %}", @"{""foo"":{""bar"":{}}}", @"YES")]
        [TestCase(@"{% if foo.bar %} YES {% endif %}", @"{""foo"":{""bar"":[]}}", @"YES")]
        [TestCase(@"{% if var %} NO {% else %} YES {% endif %}", @"{""var"":false}", @"YES")]
        [TestCase(@"{% if var %} NO {% else %} YES {% endif %}", @"{""var"":null}", @"YES")]
        [TestCase(@"{% if var %} YES {% else %} NO {% endif %}", @"{""var"":true}", @"YES")]
        [TestCase(@"{% if ""foo"" %} YES {% else %} NO {% endif %}", @"{""var"":""text""}", @"YES")]
        [TestCase(@"{% if foo.bar %} NO {% else %} YES {% endif %}", @"{""foo"":{""bar"":false}}", @"YES")]
        [TestCase(@"{% if foo.bar %} YES {% else %} NO {% endif %}", @"{""foo"":{""bar"":true}}", @"YES")]
        [TestCase(@"{% if foo.bar %} YES {% else %} NO {% endif %}", @"{""foo"":{""bar"":""text""}}", @"YES")]
        [TestCase(@"{% if foo.bar %} NO {% else %} YES {% endif %}", @"{""foo"":{""notbar"":true}}", @"YES")]
        [TestCase(@"{% if foo.bar %} NO {% else %} YES {% endif %}", @"{""foo"":{}}", @"YES")]
        [TestCase(@"{% if foo.bar %} NO {% else %} YES {% endif %}", @"{""notfoo"":{""bar"":true}}", @"YES")]
        [TestCase(@"{% if 'bob' contains 'o' %}yes{% endif %}", @"{}", @"yes")]
        [TestCase(@"{% if 'bob' contains 'f' %}yes{% else %}no{% endif %}", @"{}", @"no")]
        [TestCase(@"{% if android.name == 'Roy' %}YES{% endif %}", @"{""order"":{""items_count"":0},""android"":{""name"":""Roy""}}", @"YES")]
        [TestCase(@"{% if order.items_count == 0 %}YES{% endif %}", @"{""order"":{""items_count"":0},""android"":{""name"":""Roy""}}", @"YES")]
        [TestCase(@"{% if %}", @"{}", @"EXCEPTION:Liquid syntax error: Syntax Error in tag 'if' - Valid syntax: if [expression]")]
        [TestCase(@"{% if jerry == 1 %}", @"{}", @"EXCEPTION:Liquid syntax error: 'if' tag was never closed")]
        [TestCase(@"{% if 'gnomeslab-and-or-liquid' contains 'gnomeslab-and-or-liquid' %}yes{% endif %}", @"{}", @"yes")]
        [TestCase(@"{% if false %}{% if false %} NO {% endif %}{% endif %}", @"{}", @"")]
        [TestCase(@"{% if false %}{% if true %} NO {% endif %}{% endif %}", @"{}", @"")]
        [TestCase(@"{% if true %}{% if false %} NO {% endif %}{% endif %}", @"{}", @"")]
        [TestCase(@"{% if true %}{% if true %} YES {% endif %}{% endif %}", @"{}", @"YES")]
        [TestCase(@"{% if true %}{% if true %} YES {% else %} NO {% endif %}{% else %} NO {% endif %}", @"{}", @"YES")]
        [TestCase(@"{% if true %}{% if false %} NO {% else %} YES {% endif %}{% else %} NO {% endif %}", @"{}", @"YES")]
        [TestCase(@"{% if false %}{% if true %} NO {% else %} NONO {% endif %}{% else %} YES {% endif %}", @"{}", @"YES")]
        [TestCase(@"{% if var %} YES {% endif %}", @"{""var"":true}", @"YES")]
        [TestCase(@"{% if 1 or throw or or 1 %}yes{% endif %}", @"{}", @"EXCEPTION:Liquid syntax error: Syntax Error in tag 'if' - Valid syntax: if [expression]")]
        [TestCase(@"{% if false %} NO {% else %} YES {% endif %}", @"{}", @"YES")]
        [TestCase(@"{% if true %} YES {% else %} NO {% endif %}", @"{}", @"YES")]
        [TestCase(@"{% if ""foo"" %} YES {% else %} NO {% endif %}", @"{}", @"YES")]
        [TestCase(@"{% if null < 10 %} NO {% endif %}", @"{}", @"")]
        [TestCase(@"{% if null <= 10 %} NO {% endif %}", @"{}", @"")]
        [TestCase(@"{% if null >= 10 %} NO {% endif %}", @"{}", @"")]
        [TestCase(@"{% if null > 10 %} NO {% endif %}", @"{}", @"")]
        [TestCase(@"{% if 10 < null %} NO {% endif %}", @"{}", @"")]
        [TestCase(@"{% if 10 <= null %} NO {% endif %}", @"{}", @"")]
        [TestCase(@"{% if 10 >= null %} NO {% endif %}", @"{}", @"")]
        [TestCase(@"{% if 10 > null %} NO {% endif %}", @"{}", @"")]
        [TestCase(@"{% if 0 == 0 %}0{% elsif 1 == 1%}1{% else %}2{% endif %}", @"{}", @"0")]
        [TestCase(@"{% if 0 != 0 %}0{% elsif 1 == 1%}1{% else %}2{% endif %}", @"{}", @"1")]
        [TestCase(@"{% if 0 != 0 %}0{% elsif 1 != 1%}1{% else %}2{% endif %}", @"{}", @"2")]
        [TestCase(@"{% if false %}if{% elsif true %}elsif{% endif %}", @"{}", @"elsif")]
        [TestCase(@"{% if foo.bar %} NO {% endif %}", @"{""foo"":{}}", @"")]
        [TestCase(@"{% if a == true or b == true %} YES {% endif %}", @"{""a"":true,""b"":true}", @"YES")]
        [TestCase(@"{% if a == true or b == false %} YES {% endif %}", @"{""a"":true,""b"":true}", @"YES")]
        [TestCase(@"{% if a == false or b == false %} YES {% endif %}", @"{""a"":true,""b"":true}", @"")]
        [TestCase(@"{% if a == 'and' and b == 'or' and c == 'foo and bar' and d == 'bar or baz' and e == 'foo' and foo and bar %} YES {% endif %}", @"{""a"":""and"",""b"":""or"",""c"":""foo and bar"",""d"":""bar or baz"",""e"":""foo"",""foo"":true,""bar"":true}", @"YES")]
        [TestCase(@"{% assign v = false %}{% if v %} YES {% else %} NO {% endif %}", @"{}", @"NO")]
        [TestCase(@"{% assign v = nil %}{% if v == nil %} YES {% else %} NO {% endif %}", @"{}", @"YES")]
        [TestCase(@"{% for i in array.items %}{% continue %}{% endfor %}", @"{""array"":{""items"":[1,2,3,4,5]}}", @"")]
        [TestCase(@"{% for i in array.items %}{{ i }}{% continue %}{% endfor %}", @"{""array"":{""items"":[1,2,3,4,5]}}", @"12345")]
        [TestCase(@"{% for i in array.items %}{% continue %}{{ i }}{% endfor %}", @"{""array"":{""items"":[1,2,3,4,5]}}", @"")]
        [TestCase(@"{% for i in array.items %}{% if i > 3 %}{% continue %}{% endif %}{{ i }}{% endfor %}", @"{""array"":{""items"":[1,2,3,4,5]}}", @"123")]
        [TestCase(@"{% for i in array.items %}{% if i == 3 %}{% continue %}{% else %}{{ i }}{% endif %}{% endfor %}", @"{""array"":{""items"":[1,2,3,4,5]}}", @"1245")]
        [TestCase(@"{% for item in array %}{% for i in item %}{% if i == 1 %}{% continue %}{% endif %}{{ i }}{% endfor %}{% endfor %}", @"{""array"":[[1,2],[3,4],[5,6]]}", @"23456")]
        [TestCase(@"{% for i in array.items %}{% if i == 9999 %}{% continue %}{% endif %}{{ i }}{% endfor %}", @"{""array"":{""items"":[1,2,3,4,5]}}", @"12345")]
        [TestCase(@"{% for char in characters %}I WILL NOT BE OUTPUT{% endfor %}", @"{""characters"":""""}", @"")]
        [TestCase(@"{%for i in array.items limit:3 %}{{i}}{%endfor%}
      next
      {%for i in array.items offset:continue limit:3 %}{{i}}{%endfor%}
      next
      {%for i in array.items offset:continue limit:3 offset:1000 %}{{i}}{%endfor%}", @"{""array"":{""items"":[1,2,3,4,5,6,7,8,9,0]}}", @"123
      next
      456
      next")]
        [TestCase(@"{%for item in array%}+{%else%}-{%endfor%}", @"{""array"":[1,2,3]}", @"+++")]
        [TestCase(@"{%for item in array%}+{%else%}-{%endfor%}", @"{""array"":[]}", @"-")]
        [TestCase(@"{%for item in array%}+{%else%}-{%endfor%}", @"{""array"":null}", @"-")]
        [TestCase(@"{% for item in items %}{{item}}{% endfor %}", @"{""items"":[""@data""]}", @"12345")]
        [TestCase(@"{%for i in array offset:7 %}{{ i }}{%endfor%}", @"{""array"":[1,2,3,4,5,6,7,8,9,0]}", @"890")]
        [TestCase(@"{% for a in (1..2) %}o{% for b in empty %}{% endfor %}{% endfor %}", @"{}", @"oo")]
        [TestCase(@"{%for i in array limit: limit offset: offset %}{{ i }}{%endfor%}", @"{""array"":[1,2,3,4,5,6,7,8,9,0],""limit"":2,""offset"":2}", @"34")]
        [TestCase(@"{%for i in array limit: x offset: y %}{{ i }}{%endfor%}", @"{""array"":[1,2,3,4,5,6,7,8,9,0],""x"":2,""y"":2}", @"34")]
        [TestCase(@"{%for item in array%}{%for i in item%}{{ i }}{%endfor%}{%endfor%}", @"{""array"":[[1,2],[3,4],[5,6]]}", @"123456")]
        [TestCase(@"{% for inner in outer %}{{ forloop.parentloop.index }}.{{ forloop.index }} {% endfor %}", @"{""outer"":[[1,1,1],[1,1,1]]}", @".1 .2")]
        [TestCase(@"{% for       item   in   items %}{{item}}{% endfor %}", @"{""items"":[1,2,3,4,5]}", @"12345")]
        [TestCase(@"{% for i in array.items %}{% break %}{% endfor %}", @"{""array"":{""items"":[1,2,3,4,5,6,7,8,9,10]}}", @"")]
        [TestCase(@"{% for i in array.items %}{{ i }}{% break %}{% endfor %}", @"{""array"":{""items"":[1,2,3,4,5,6,7,8,9,10]}}", @"1")]
        [TestCase(@"{% for i in array.items %}{% break %}{{ i }}{% endfor %}", @"{""array"":{""items"":[1,2,3,4,5,6,7,8,9,10]}}", @"")]
        [TestCase(@"{% for i in array.items %}{{ i }}{% if i > 3 %}{% break %}{% endif %}{% endfor %}", @"{""array"":{""items"":[1,2,3,4,5,6,7,8,9,10]}}", @"1234")]
        [TestCase(@"{% for item in array %}{% for i in item %}{% if i == 1 %}{% break %}{% endif %}{{ i }}{% endfor %}{% endfor %}", @"{""array"":[[1,2],[3,4],[5,6]]}", @"3456")]
        [TestCase(@"{% for i in array.items %}{% if i == 9999 %}{% break %}{% endif %}{{ i }}{% endfor %}", @"{""array"":{""items"":[1,2,3,4,5]}}", @"12345")]
        [TestCase(@"{%for item in (1..foobar.value) %} {{item}} {%endfor%}", @"{""foobar"":[]}", @"1  2  3")]
        [TestCase(@"{%for item in (1..foobar.value) %} {{item}} {%endfor%}", @"{""foobar"":{""value"":3}}", @"1  2  3")]
        [TestCase(@"{%for item in array%} yo {%endfor%}", @"{""array"":[1,2,3,4]}", @"yo  yo  yo  yo")]
        [TestCase(@"{%for item in array%}yo{%endfor%}", @"{""array"":[1,2]}", @"yoyo")]
        [TestCase(@"{%for item in array%} yo {%endfor%}", @"{""array"":[1]}", @"yo")]
        [TestCase(@"{%for item in array%}{%endfor%}", @"{""array"":[1,2]}", @"")]
        [TestCase(@"{%for item in array%}
  yo
{%endfor%}", @"{""array"":[1,2,3]}", @"yo

  yo

  yo")]
        [TestCase(@"{%for val in string%}{{val}}{%endfor%}", @"{""string"":""test string""}", @"test string")]
        [TestCase(@"{%for val in string limit:1%}{{val}}{%endfor%}", @"{""string"":""test string""}", @"test string")]
        [TestCase(@"{%for val in string%}{{forloop.name}}-{{forloop.index}}-{{forloop.length}}-{{forloop.index0}}-{{forloop.rindex}}-{{forloop.rindex0}}-{{forloop.first}}-{{forloop.last}}-{{val}}{%endfor%}", @"{""string"":""test string""}", @"val-string-1-1-0-1-0-true-true-test string")]
        [TestCase(@"{%for item in array%} {{forloop.index}}/{{forloop.length}} {%endfor%}", @"{""array"":[1,2,3]}", @"1/3  2/3  3/3")]
        [TestCase(@"{%for item in array%} {{forloop.index}} {%endfor%}", @"{""array"":[1,2,3]}", @"1  2  3")]
        [TestCase(@"{%for item in array%} {{forloop.index0}} {%endfor%}", @"{""array"":[1,2,3]}", @"0  1  2")]
        [TestCase(@"{%for item in array%} {{forloop.rindex0}} {%endfor%}", @"{""array"":[1,2,3]}", @"2  1  0")]
        [TestCase(@"{%for item in array%} {{forloop.rindex}} {%endfor%}", @"{""array"":[1,2,3]}", @"3  2  1")]
        [TestCase(@"{%for item in array%} {{forloop.first}} {%endfor%}", @"{""array"":[1,2,3]}", @"true  false  false")]
        [TestCase(@"{%for item in array%} {{forloop.last}} {%endfor%}", @"{""array"":[1,2,3]}", @"false  false  true")]
        [TestCase(@"{% for inner in outer %}{% for k in inner %}{{ forloop.parentloop.index }}.{{ forloop.index }} {% endfor %}{% endfor %}", @"{""outer"":[[1,1,1],[1,1,1]]}", @"1.1 1.2 1.3 2.1 2.2 2.3")]
        [TestCase(@"{%for item in array%} {{item}} {%endfor%}", @"{""array"":[1,2,3]}", @"1  2  3")]
        [TestCase(@"{%for item in array%}{{item}}{%endfor%}", @"{""array"":[1,2,3]}", @"123")]
        [TestCase(@"{% for item in array %}{{item}}{% endfor %}", @"{""array"":[1,2,3]}", @"123")]
        [TestCase(@"{%for item in array%}{{item}}{%endfor%}", @"{""array"":[""a"",""b"",""c"",""d""]}", @"abcd")]
        [TestCase(@"{%for item in array%}{{item}}{%endfor%}", @"{""array"":[""a"","" "",""b"","" "",""c""]}", @"a b c")]
        [TestCase(@"{%for item in array%}{{item}}{%endfor%}", @"{""array"":[""a"","""",""b"","""",""c""]}", @"abc")]
        [TestCase(@"{% for item in items limit:1 %}{{item}}{% endfor %}", @"{""items"":[""@data""]}", @"1")]
        [TestCase(@"{%for i in array.items limit:3 %}{{i}}{%endfor%}
      next
      {%for i in array.items offset:continue limit:3 %}{{i}}{%endfor%}
      next
      {%for i in array.items offset:continue limit:1000 %}{{i}}{%endfor%}", @"{""array"":{""items"":[1,2,3,4,5,6,7,8,9,0]}}", @"123
      next
      456
      next
      7890")]
        [TestCase(@"{% for item in items offset:2 limit:2 %}{{item}}{% endfor %}", @"{""items"":[""@data""]}", @"34")]
        [TestCase(@"{% for item in items offset:2 limit:2 %}{{item}}{% endfor %}", @"{""items"":[1,2,3,4,5]}", @"34")]
        [TestCase(@"{%for i in array limit:2 %}{{ i }}{%endfor%}", @"{""array"":[1,2,3,4,5,6,7,8,9,0]}", @"12")]
        [TestCase(@"{%for i in array limit:4 %}{{ i }}{%endfor%}", @"{""array"":[1,2,3,4,5,6,7,8,9,0]}", @"1234")]
        [TestCase(@"{%for i in array limit:4 offset:2 %}{{ i }}{%endfor%}", @"{""array"":[1,2,3,4,5,6,7,8,9,0]}", @"3456")]
        [TestCase(@"{%for i in array limit: 4 offset: 2 %}{{ i }}{%endfor%}", @"{""array"":[1,2,3,4,5,6,7,8,9,0]}", @"3456")]
        [TestCase(@"{%for item in array%}{% if forloop.first %}+{% else %}-{% endif %}{%endfor%}", @"{""array"":[1,2,3]}", @"+--")]
        [TestCase(@"{%for item in array reversed %}{{item}}{%endfor%}", @"{""array"":[1,2,3]}", @"321")]
        [TestCase(@"{%for i in array.items limit: 3 %}{{i}}{%endfor%}
      next
      {%for i in array.items offset:continue limit: 3 %}{{i}}{%endfor%}
      next
      {%for i in array.items offset:continue limit: 3 %}{{i}}{%endfor%}", @"{""array"":{""items"":[1,2,3,4,5,6,7,8,9,0]}}", @"123
      next
      456
      next
      789")]
        [TestCase(@"{%for item in (1..3) %} {{item}} {%endfor%}", @"{}", @"1  2  3")]
        [TestCase(@"{% for item in items offset:2 limit:2 %}{{item}}{% endfor %}", @"{""items"":[""@data""]}", @"34")]
        [TestCase(@"{%for item in (1..foobar) %} {{item}} {%endfor%}", @"{""foobar"":3}", @"1  2  3")]
        [TestCase(@"{%for i in array.items limit:3 %}{{i}}{%endfor%}
      next
      {%for i in array.items offset:continue limit:3 %}{{i}}{%endfor%}
      next
      {%for i in array.items offset:continue limit:1 %}{{i}}{%endfor%}", @"{""array"":{""items"":[1,2,3,4,5,6,7,8,9,0]}}", @"123
      next
      456
      next
      7")]
        [TestCase(@"{% if true == empty %}?{% endif %}", @"{}", @"")]
        [TestCase(@"{% if true == null %}?{% endif %}", @"{}", @"")]
        [TestCase(@"{% if empty == true %}?{% endif %}", @"{}", @"")]
        [TestCase(@"{% if null == true %}?{% endif %}", @"{}", @"")]
        [TestCase(@"{%assign var2 = var[""a:b c""].paged %}var2: {{var2}}", @"{""var"":{""a:b c"":{""paged"":""1""}}}", @"var2: 1")]
        [TestCase(@"{% case a.size %}{% when 1 %}1{% when 2 %}2{% endcase %}", @"{""a"":[]}", @"")]
        [TestCase(@"{% case a.size %}{% when 1 %}1{% when 2 %}2{% endcase %}", @"{""a"":[1]}", @"1")]
        [TestCase(@"{% case a.size %}{% when 1 %}1{% when 2 %}2{% endcase %}", @"{""a"":[1,1]}", @"2")]
        [TestCase(@"{% case a.size %}{% when 1 %}1{% when 2 %}2{% endcase %}", @"{""a"":[1,1,1]}", @"")]
        [TestCase(@"{% case a.size %}{% when 1 %}1{% when 2 %}2{% endcase %}", @"{""a"":[1,1,1,1]}", @"")]
        [TestCase(@"{% case a.size %}{% when 1 %}1{% when 2 %}2{% endcase %}", @"{""a"":[1,1,1,1,1]}", @"")]
        [TestCase(@"var2:{{var2}} {%assign var2 = var%} var2:{{var2}}", @"{""var"":""content""}", @"var2:  var2:content")]
        [TestCase(@"{%for i in (1..2) %}{% assign a = ""variable""%}{% endfor %}{{a}}", @"{}", @"variable")]
        [TestCase(@"{% case false %}{% when %}true{% endcase %}", @"{}", @"EXCEPTION:Liquid syntax error: Syntax Error in tag 'case' - Valid when condition: {% when [condition] [or condition2...] %}")]
        [TestCase(@"{% case false %}{% huh %}true{% endcase %}", @"{}", @"EXCEPTION:Liquid syntax error: Unknown tag 'huh'")]
        [TestCase(@"{% case a.size %}{% when 1 %}1{% when 2 %}2{% else %}else{% endcase %}", @"{""a"":[]}", @"else")]
        [TestCase(@"{% case a.size %}{% when 1 %}1{% when 2 %}2{% else %}else{% endcase %}", @"{""a"":[1]}", @"1")]
        [TestCase(@"{% case a.size %}{% when 1 %}1{% when 2 %}2{% else %}else{% endcase %}", @"{""a"":[1,1]}", @"2")]
        [TestCase(@"{% case a.size %}{% when 1 %}1{% when 2 %}2{% else %}else{% endcase %}", @"{""a"":[1,1,1]}", @"else")]
        [TestCase(@"{% case a.size %}{% when 1 %}1{% when 2 %}2{% else %}else{% endcase %}", @"{""a"":[1,1,1,1]}", @"else")]
        [TestCase(@"{% case a.size %}{% when 1 %}1{% when 2 %}2{% else %}else{% endcase %}", @"{""a"":[1,1,1,1,1]}", @"else")]
        [TestCase(@"{{ var2 }}{% capture var2 %}{{ var }} foo {% endcapture %}{{ var2 }}{{ var2 }}", @"{""var"":""content""}", @"content foo content foo")]
        [TestCase(@"the comment block should be removed {%comment%} be gone.. {%endcomment%} .. right?", @"{}", @"the comment block should be removed  .. right?")]
        [TestCase(@"{%comment%}{%endcomment%}", @"{}", @"")]
        [TestCase(@"{%comment%}{% endcomment %}", @"{}", @"")]
        [TestCase(@"{% comment %}{%endcomment%}", @"{}", @"")]
        [TestCase(@"{% comment %}{% endcomment %}", @"{}", @"")]
        [TestCase(@"{%comment%}comment{%endcomment%}", @"{}", @"")]
        [TestCase(@"{% comment %}comment{% endcomment %}", @"{}", @"")]
        [TestCase(@"{% comment %} 1 {% comment %} 2 {% endcomment %} 3 {% endcomment %}", @"{}", @"")]
        [TestCase(@"{%comment%}{%blabla%}{%endcomment%}", @"{}", @"")]
        [TestCase(@"{% comment %}{% blabla %}{% endcomment %}", @"{}", @"")]
        [TestCase(@"{%comment%}{% endif %}{%endcomment%}", @"{}", @"")]
        [TestCase(@"{% comment %}{% endwhatever %}{% endcomment %}", @"{}", @"")]
        [TestCase(@"{% comment %}{% raw %} {{%%%%}}  }} { {% endcomment %} {% comment {% endraw %} {% endcomment %}", @"{}", @"")]
        [TestCase(@"foo{%comment%}comment{%endcomment%}bar", @"{}", @"foobar")]
        [TestCase(@"foo{% comment %}comment{% endcomment %}bar", @"{}", @"foobar")]
        [TestCase(@"foo{%comment%} comment {%endcomment%}bar", @"{}", @"foobar")]
        [TestCase(@"foo{% comment %} comment {% endcomment %}bar", @"{}", @"foobar")]
        [TestCase(@"foo {%comment%} {%endcomment%} bar", @"{}", @"foo  bar")]
        [TestCase(@"foo {%comment%}comment{%endcomment%} bar", @"{}", @"foo  bar")]
        [TestCase(@"foo {%comment%} comment {%endcomment%} bar", @"{}", @"foo  bar")]
        [TestCase(@"foo{%comment%}
                                     {%endcomment%}bar", @"{}", @"foobar")]
        [TestCase(@"{%cycle ""one"", ""two""%}", @"{}", @"one")]
        [TestCase(@"{%cycle ""one"", ""two""%} {%cycle ""one"", ""two""%}", @"{}", @"one two")]
        [TestCase(@"{%cycle """", ""two""%} {%cycle """", ""two""%}", @"{}", @"two")]
        [TestCase(@"{%cycle ""one"", ""two""%} {%cycle ""one"", ""two""%} {%cycle ""one"", ""two""%}", @"{}", @"one two one")]
        [TestCase(@"{%cycle ""text-align: left"", ""text-align: right"" %} {%cycle ""text-align: left"", ""text-align: right""%}", @"{}", @"text-align: left text-align: right")]
        [TestCase(@"{% assign a = ""variable""%}{{a}}", @"{}", @"variable")]
        [TestCase(@"{% case condition %}{% when 1 or 2 or 3 %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":1}", @"its 1 or 2 or 3")]
        [TestCase(@"{% case condition %}{% when 1 or 2 or 3 %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":2}", @"its 1 or 2 or 3")]
        [TestCase(@"{% case condition %}{% when 1 or 2 or 3 %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":3}", @"its 1 or 2 or 3")]
        [TestCase(@"{% case condition %}{% when 1 or 2 or 3 %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":4}", @"its 4")]
        [TestCase(@"{% case condition %}{% when 1 or 2 or 3 %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":5}", @"")]
        [TestCase(@"{% case condition %}{% when 1 or ""string"" or null %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":1}", @"its 1 or 2 or 3")]
        [TestCase(@"{% case condition %}{% when 1 or ""string"" or null %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":""string""}", @"its 1 or 2 or 3")]
        [TestCase(@"{% case condition %}{% when 1 or ""string"" or null %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":null}", @"its 1 or 2 or 3")]
        [TestCase(@"{% case condition %}{% when 1 or ""string"" or null %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":""something else""}", @"")]
        [TestCase(@"{%cycle 1: ""one"", ""two"" %} {%cycle 2: ""one"", ""two"" %} {%cycle 1: ""one"", ""two"" %} {%cycle 2: ""one"", ""two"" %} {%cycle 1: ""one"", ""two"" %} {%cycle 2: ""one"", ""two"" %}", @"{}", @"one one two two one one")]
        [TestCase(@"{% case condition %}{% when 1 %} its 1 {% when 2 %} its 2 {% endcase %}", @"{""condition"":2}", @"its 2")]
        [TestCase(@"{% case condition %}{% when 1 %} its 1 {% when 2 %} its 2 {% endcase %}", @"{""condition"":1}", @"its 1")]
        [TestCase(@"{% case condition %}{% when 1 %} its 1 {% when 2 %} its 2 {% endcase %}", @"{""condition"":3}", @"")]
        [TestCase(@"{% case condition %}{% when ""string here"" %} hit {% endcase %}", @"{""condition"":""string here""}", @"hit")]
        [TestCase(@"{% case condition %}{% when ""string here"" %} hit {% endcase %}", @"{""condition"":""bad string here""}", @"")]
        [TestCase(@"{% assign a = """"%}{{a}}", @"{}", @"")]
        [TestCase(@"a-b:{{a-b}} {%assign a-b = 2 %}a-b:{{a-b}}", @"{""a-b"":""1""}", @"a-b:1 a-b:2")]
        [TestCase(@"{%for item in array%}{%ifchanged%}{{item}}{% endifchanged %}{%endfor%}", @"{""array"":[1,1,2,2,3,3]}", @"123")]
        [TestCase(@"{%for item in array%}{%ifchanged%}{{item}}{% endifchanged %}{%endfor%}", @"{""array"":[1,1,1,1]}", @"1")]
        [TestCase(@"{% case a.empty? %}{% when true %}true{% when false %}false{% else %}else{% endcase %}", @"{}", @"else")]
        [TestCase(@"{% case false %}{% when true %}true{% when false %}false{% else %}else{% endcase %}", @"{}", @"false")]
        [TestCase(@"{% case true %}{% when true %}true{% when false %}false{% else %}else{% endcase %}", @"{}", @"true")]
        [TestCase(@"{% case NULL %}{% when true %}true{% when false %}false{% else %}else{% endcase %}", @"{}", @"else")]
        [TestCase(@"0{%
for i in (1..3)
%} {{
i
}}{%
endfor
%}", @"{}", @"0 1 2 3")]
        [TestCase(@"{% case condition %}{% when 1, 2, 3 %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":1}", @"its 1 or 2 or 3")]
        [TestCase(@"{% case condition %}{% when 1, 2, 3 %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":2}", @"its 1 or 2 or 3")]
        [TestCase(@"{% case condition %}{% when 1, 2, 3 %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":3}", @"its 1 or 2 or 3")]
        [TestCase(@"{% case condition %}{% when 1, 2, 3 %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":4}", @"its 4")]
        [TestCase(@"{% case condition %}{% when 1, 2, 3 %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":5}", @"")]
        [TestCase(@"{% case condition %}{% when 1, ""string"", null %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":1}", @"its 1 or 2 or 3")]
        [TestCase(@"{% case condition %}{% when 1, ""string"", null %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":""string""}", @"its 1 or 2 or 3")]
        [TestCase(@"{% case condition %}{% when 1, ""string"", null %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":null}", @"its 1 or 2 or 3")]
        [TestCase(@"{% case condition %}{% when 1, ""string"", null %} its 1 or 2 or 3 {% when 4 %} its 4 {% endcase %}", @"{""condition"":""something else""}", @"")]
        [TestCase(@"this text should come out of the template without change...", @"{}", @"this text should come out of the template without change...")]
        [TestCase(@"blah", @"{}", @"blah")]
        [TestCase(@"<blah>", @"{}", @"<blah>")]
        [TestCase(@"|,.:", @"{}", @"|,.:")]
        [TestCase(@"", @"{}", @"")]
        [TestCase(@"this shouldnt see any transformation either but has multiple lines
              as you can clearly see here ...", @"{}", @"this shouldnt see any transformation either but has multiple lines
              as you can clearly see here ...")]
        [TestCase(@"{{ var2 }}{% capture %}{{ var }} foo {% endcapture %}{{ var2 }}{{ var2 }}", @"{""var"":""content""}", @"EXCEPTION:Liquid syntax error: Syntax Error in 'capture' - Valid syntax: capture [var]")]
        [TestCase(@"{% case condition %}{% when 5 %} hit {% else %} else {% endcase %}", @"{""condition"":5}", @"hit")]
        [TestCase(@"{% case condition %}{% when 5 %} hit {% else %} else {% endcase %}", @"{""condition"":6}", @"else")]
        [TestCase(@"{% case condition %} {% when 5 %} hit {% else %} else {% endcase %}", @"{""condition"":6}", @"else")]
        [TestCase(@"{%cycle var1: ""one"", ""two"" %} {%cycle var2: ""one"", ""two"" %} {%cycle var1: ""one"", ""two"" %} {%cycle var2: ""one"", ""two"" %} {%cycle var1: ""one"", ""two"" %} {%cycle var2: ""one"", ""two"" %}", @"{""var1"":1,""var2"":2}", @"one one two two one one")]
        [TestCase(@"array has {{ array.size }} elements", @"{""array"":[1,2,3,4]}", @"array has 4 elements")]
        [TestCase(@"{%cycle 1,2%} {%cycle 1,2%} {%cycle 1,2%} {%cycle 1,2,3%} {%cycle 1,2,3%} {%cycle 1,2,3%} {%cycle 1,2,3%}", @"{}", @"1 2 1 1 2 3 1")]
        [TestCase(@"hash has {{ hash.size }} elements", @"{""hash"":{""a"":1,""b"":2,""c"":3,""d"":4}}", @"hash has 4 elements")]
        [TestCase(@"{% include 'locale_variables' echo1: echo1, echo2: more_echos.echo2 %}", @"{""echo1"":""test123"",""more_echos"":{""echo2"":""test321""}}", @"Locale: test123 test321")]
        [TestCase(@"{% include template %}", @"{""template"":""Test123""}", @"Test123")]
        [TestCase(@"{% include template %}", @"{""template"":""Test321""}", @"Test321")]
        [TestCase(@"{% include template for product %}", @"{""template"":""product"",""product"":{""title"":""Draft 151cm""}}", @"Product: Draft 151cm")]
        [TestCase(@"{% include 'locale_variables' echo1: 'test123' %}", @"{}", @"Locale: test123")]
        [TestCase(@"{% include 'body' %}", @"{}", @"body body_detail")]
        [TestCase(@"{% include 'nested_template' %}", @"{}", @"header body body_detail footer")]
        [TestCase(@"{% include 'product' %}", @"{""product"":{""title"":""Draft 151cm""}}", @"Product: Draft 151cm")]
        [TestCase(@"{% include 'locale_variables' echo1: 'test123', echo2: 'test321' %}", @"{}", @"Locale: test123 test321")]
        [TestCase(@"{% if true %}{% include 'foo_if_true' %}{% endif %}", @"{}", @"foo_if_true")]
        [TestCase(@"{% include 'assignments' %}{{ foo }}", @"{}", @"bar")]
        [TestCase(@"{% include 'product' with products[0] %}", @"{""products"":[{""title"":""Draft 151cm""},{""title"":""Element 155cm""}]}", @"Product: Draft 151cm")]
        [TestCase(@"{% include 'nested_product_template' with product %}", @"{""product"":{""title"":""Draft 151cm""}}", @"Product: Draft 151cm details")]
        [TestCase(@"{% include 'nested_product_template' for products %}", @"{""products"":[{""title"":""Draft 151cm""},{""title"":""Element 155cm""}]}", @"Product: Draft 151cm details Product: Element 155cm details")]
        [TestCase(@"{% include 'product' for products %}", @"{""products"":[{""title"":""Draft 151cm""},{""title"":""Element 155cm""}]}", @"Product: Draft 151cm Product: Element 155cm")]
        [TestCase(@"{% assign page = 'pick_a_source' %}{% include page %}", @"{}", @"from TestFileSystem")]
        [TestCase(@"{% assign page = 'product' %}{% include page %}", @"{""product"":{""title"":""Draft 151cm""}}", @"Product: Draft 151cm")]
        [TestCase(@"{% assign page = 'product' %}{% include page for foo %}", @"{""foo"":{""title"":""Draft 151cm""}}", @"Product: Draft 151cm")]
        [TestCase(@"{% raw %}{% comment %} test {% endcomment %}{% endraw %}", @"{}", @"{% comment %} test {% endcomment %}")]
        [TestCase(@"{% raw %} Foobar {% invalid {% endraw %}", @"{}", @"Foobar {% invalid")]
        [TestCase(@"{% raw %} Foobar invalid %} {% endraw %}", @"{}", @"Foobar invalid %}")]
        [TestCase(@"{% raw %} Foobar {{ invalid {% endraw %}", @"{}", @"Foobar {{ invalid")]
        [TestCase(@"{% raw %} Foobar invalid }} {% endraw %}", @"{}", @"Foobar invalid }}")]
        [TestCase(@"{% raw %} Foobar {% invalid {% {% endraw {% endraw %}", @"{}", @"Foobar {% invalid {% {% endraw")]
        [TestCase(@"{% raw %} Foobar {% {% {% {% endraw %}", @"{}", @"Foobar {% {% {%")]
        [TestCase(@"{% raw %} test {% raw %} {% {% endraw %}endraw %}", @"{}", @"test {% raw %} {% endraw %}")]
        [TestCase(@"{% raw %} Foobar {{ invalid {% endraw %}{{ 1 }}", @"{}", @"Foobar {{ invalid 1")]
        [TestCase(@"{% raw %}{{ test }}{% endraw %}", @"{}", @"{{ test }}")]
        //[TestCase(@"{% continue %}", @"{}", @"")]
        [TestCase(@"{% capture 'var' %}test string{% endcapture %}{{var}}", @"{}", @"test string")]
        [TestCase(@"{% unless true %} NO {% else %} YES {% endunless %}", @"{}", @"YES")]
        [TestCase(@"{% unless false %} YES {% else %} NO {% endunless %}", @"{}", @"YES")]
        [TestCase(@"{% unless ""foo"" %} NO {% else %} YES {% endunless %}", @"{}", @"YES")]
        [TestCase(@"{% unless true %} this text should not go into the output {% endunless %}", @"{}", @"")]
        [TestCase(@"{% unless false %} this text should go into the output {% endunless %}", @"{}", @"this text should go into the output")]
        [TestCase(@"{% unless true %} you suck {% endunless %} {% unless false %} you rock {% endunless %}?", @"{}", @"you rock ?")]
        [TestCase(@"{% for i in choices %}{% unless i %} {{ forloop.index }} {% else %} TRUE {% endunless %}{% endfor %}", @"{""choices"":[1,null,false]}", @"TRUE  2  3")]
        [TestCase(@"{% for i in choices %}{% unless i %}{{ forloop.index }}{% endunless %}{% endfor %}", @"{""choices"":[1,null,false]}", @"23")]
        [TestCase(@"{% if a == 'foo' or (b == 'bar' and c == 'baz') or false %} YES {% endif %}", @"{""b"":""bar"",""c"":""baz""}", @"YES")]
        //[TestCase(@"{% assign 123foo = 'bar' %}{{ 123foo }}", @"{}", @"bar")]
        //[TestCase(@"{% assign 123 = 'bar' %}{{ 123 }}", @"{}", @"123")]
        [TestCase(@"{% if true && false %} YES {% endif %}", @"{}", @"YES")]
        [TestCase(@"{% if false || true %} YES {% endif %}", @"{}", @"")]
        //[TestCase(@"{% for i in (1...5) %}{{ i }}{% endfor %}", @"{}", @"12345")]
        [TestCase(@"{{ 'hi there' | split$$$:' ' | first }}", @"{}", @"hi")]
        [TestCase(@"{{ 'X' | downcase) }}", @"{}", @"x")]
        [TestCase(@"{{ 'hi there' | split:""t"""" | reverse | first}}", @"{}", @"here")]
        [TestCase(@"{{ 'hi there' | split:""t"""" | remove:""i"" | first}}", @"{}", @"hi")]
        [TestCase(@"{{ foo | map: ""whatever"" }}", @"{""foo"":[""woot: 0""]}", @"woot: 1")]
        [TestCase(@"{{ 3 | modulo:2 }}", @"{}", @"1")]
        [TestCase(@"{{ 1 | modulo: 0 }}", @"{}", @"EXCEPTION:Liquid error: divided by 0")]
        [TestCase(@"{{ ary | map:'foo' | map:'bar' }}", @"{""ary"":[{""foo"":{""bar"":""a""}},{""foo"":{""bar"":""b""}},{""foo"":{""bar"":""c""}}]}", @"abc")]
        [TestCase(@"{{ source | strip_newlines }}", @"{""source"":""a\nb\nc""}", @"abc")]
        [TestCase(@"{{ source | strip_newlines }}", @"{""source"":""a\r\nb\nc""}", @"abc")]
        [TestCase(@"{{ thing | map: ""foo"" | map: ""bar"" }}", @"{""thing"":{""foo"":[{""bar"":42},{""bar"":17}]}}", @"4217")]
        [TestCase(@"{{ 'foo|bar' | remove: '|' }}", @"{}", @"foobar")]
        [TestCase(@"{{ source | strip }}", @"{""source"":"" ab c  ""}", @"ab c")]
        [TestCase(@"{{ source | strip }}", @"{""source"":"" \tab c  \n \t""}", @"ab c")]
        [TestCase(@"{{ 1 | plus:1 }}", @"{}", @"2")]
        [TestCase(@"{{ '1' | plus:'1.0' }}", @"{}", @"2.0")]
        [TestCase(@"{{ foo | sort: ""bar"" | map: ""foo"" }}", @"{""foo"":[]}", @"213")]
        [TestCase(@"{{ input | floor }}", @"{""input"":4.6}", @"4")]
        [TestCase(@"{{ '4.3' | floor }}", @"{}", @"4")]
        [TestCase(@"{{ 1.0 | divided_by: 0.0 | floor }}", @"{}", @"EXCEPTION:Liquid error: Computation results to 'Infinity'")]
        [TestCase(@"{{ foo | map: ""foo"" }}", @"{""foo"":[]}", @"123")]
        [TestCase(@"{{ a | prepend: 'a'}}", @"{""a"":""bc"",""b"":""a""}", @"abc")]
        [TestCase(@"{{ a | prepend: b}}", @"{""a"":""bc"",""b"":""a""}", @"abc")]
        [TestCase(@"{{ source | lstrip }}", @"{""source"":"" ab c  ""}", @"ab c")]
        [TestCase(@"{{ source | lstrip }}", @"{""source"":"" \tab c  \n \t""}", @"ab c")]
        [TestCase(@"{{ 3 | times:4 }}", @"{}", @"12")]
        [TestCase(@"{{ 'foo' | times:4 }}", @"{}", @"0")]
        [TestCase(@"{{ '2.1' | times:3 | replace: '.','-' | plus:0}}", @"{}", @"6")]
        [TestCase(@"{{ 0.0725 | times:100 }}", @"{}", @"7.25")]
        [TestCase(@"{{ input | round }}", @"{""input"":4.6}", @"5")]
        [TestCase(@"{{ '4.3' | round }}", @"{}", @"4")]
        [TestCase(@"{{ input | round: 2 }}", @"{""input"":4.5612}", @"4.56")]
        [TestCase(@"{{ 1.0 | divided_by: 0.0 | round }}", @"{}", @"EXCEPTION:Liquid error: Infinity")]
        [TestCase(@"{{ 'a' | to_number }}", @"{}", @"a")]
        [TestCase(@"{{ foo | first }}", @"{""foo"":[""#<ThingWithToLiquid:0x00000002d315b0>""]}", @"foobar")]
        [TestCase(@"{{ foo | last }}", @"{""foo"":[""#<ThingWithToLiquid:0x00000002d21020>""]}", @"foobar")]
        [TestCase(@"{{ procs | map: ""test"" }}", @"{""procs"":[""#<Proc:0x00000002d19758@/home/bridge/work/liquid/test/integration/standard_filter_test.rb:223>""]}", @"testfoo")]
        [TestCase(@"{{ source | rstrip }}", @"{""source"":"" ab c  ""}", @"ab c")]
        [TestCase(@"{{ source | rstrip }}", @"{""source"":"" \tab c  \n \t""}", @"ab c")]
        [TestCase(@"{{ input | ceil }}", @"{""input"":4.6}", @"5")]
        [TestCase(@"{{ '4.3' | ceil }}", @"{}", @"5")]
        [TestCase(@"{{ 1.0 | divided_by: 0.0 | ceil }}", @"{}", @"EXCEPTION:Liquid error: Computation results to 'Infinity'")]
        [TestCase(@"{{ 12 | divided_by:3 }}", @"{}", @"4")]
        [TestCase(@"{{ 14 | divided_by:3 }}", @"{}", @"4")]
        [TestCase(@"{{ 15 | divided_by:3 }}", @"{}", @"5")]
        [TestCase(@"{{ 2.0 | divided_by:4 }}", @"{}", @"0.5")]
        [TestCase(@"{{ 1 | modulo: 0 }}", @"{}", @"EXCEPTION:Liquid error: divided by 0")]
        [TestCase(@"{{ input | minus:operand }}", @"{""input"":5,""operand"":1}", @"4")]
        [TestCase(@"{{ '4.3' | minus:'2' }}", @"{}", @"2.3")]
        [TestCase(@"{{ 'a a a a' | remove_first: 'a ' }}", @"{}", @"a a a")]
        [TestCase(@"{{ a | append: 'd'}}", @"{""a"":""bc"",""b"":""d""}", @"bcd")]
        [TestCase(@"{{ a | append: b}}", @"{""a"":""bc"",""b"":""d""}", @"bcd")]
        [TestCase(@"{{ ""foo"" | map: ""__id__"" }}", @"{}", @"")]
        [TestCase(@"{{ ""foo"" | map: ""inspect"" }}", @"{}", @"")]
        [TestCase(@"{{ source | newline_to_br }}", @"{""source"":""a\nb\nc""}", @"a<br />
b<br />
c")]
        [TestCase(@"{{ '1 1 1 1' | replace_first: '1', 2 }}", @"{}", @"2 1 1 1")]
        [TestCase(@"{% assign key = 'foo' %}{{ thing | map: key | map: 'bar' }}", @"{""thing"":{""foo"":{""bar"":42}}}", @"42")]
        [TestCase(@"{% tablerow n in numbers cols:3%} {{n}} {% endtablerow %}", @"{""numbers"":[""@array""]}", @"<tr class=""row1"">
<td class=""col1""> 1 </td><td class=""col2""> 2 </td><td class=""col3""> 3 </td></tr>
<tr class=""row2""><td class=""col1""> 4 </td><td class=""col2""> 5 </td><td class=""col3""> 6 </td></tr>")]
        [TestCase(@"{% tablerow n in numbers cols:2%}{{tablerowloop.col}}{% endtablerow %}", @"{""numbers"":[1,2,3,4,5,6]}", @"<tr class=""row1"">
<td class=""col1"">1</td><td class=""col2"">2</td></tr>
<tr class=""row2""><td class=""col1"">1</td><td class=""col2"">2</td></tr>
<tr class=""row3""><td class=""col1"">1</td><td class=""col2"">2</td></tr>")]
        [TestCase(@"{% tablerow char in characters cols:3 %}I WILL NOT BE OUTPUT{% endtablerow %}", @"{""characters"":""""}", @"<tr class=""row1"">
</tr>")]
        [TestCase(@"{% tablerow n in numbers cols:3 offset:1 limit:6%} {{n}} {% endtablerow %}", @"{""numbers"":[0,1,2,3,4,5,6,7]}", @"<tr class=""row1"">
<td class=""col1""> 1 </td><td class=""col2""> 2 </td><td class=""col3""> 3 </td></tr>
<tr class=""row2""><td class=""col1""> 4 </td><td class=""col2""> 5 </td><td class=""col3""> 6 </td></tr>")]
        [TestCase(@"{% tablerow n in numbers cols:3%} {{n}} {% endtablerow %}", @"{""numbers"":[1,2,3,4,5,6]}", @"<tr class=""row1"">
<td class=""col1""> 1 </td><td class=""col2""> 2 </td><td class=""col3""> 3 </td></tr>
<tr class=""row2""><td class=""col1""> 4 </td><td class=""col2""> 5 </td><td class=""col3""> 6 </td></tr>")]
        [TestCase(@"{% tablerow n in numbers cols:3%} {{n}} {% endtablerow %}", @"{""numbers"":[]}", @"<tr class=""row1"">
</tr>")]
        [TestCase(@"{% tablerow n in numbers cols:5%} {{n}} {% endtablerow %}", @"{""numbers"":[1,2,3,4,5,6]}", @"<tr class=""row1"">
<td class=""col1""> 1 </td><td class=""col2""> 2 </td><td class=""col3""> 3 </td><td class=""col4""> 4 </td><td class=""col5""> 5 </td></tr>
<tr class=""row2""><td class=""col1""> 6 </td></tr>")]
        [TestCase(@"{% tablerow n in collections.frontpage cols:3%} {{n}} {% endtablerow %}", @"{""collections"":{""frontpage"":[1,2,3,4,5,6]}}", @"<tr class=""row1"">
<td class=""col1""> 1 </td><td class=""col2""> 2 </td><td class=""col3""> 3 </td></tr>
<tr class=""row2""><td class=""col1""> 4 </td><td class=""col2""> 5 </td><td class=""col3""> 6 </td></tr>")]
        [TestCase(@"{% tablerow n in collections['frontpage'] cols:3%} {{n}} {% endtablerow %}", @"{""collections"":{""frontpage"":[1,2,3,4,5,6]}}", @"<tr class=""row1"">
<td class=""col1""> 1 </td><td class=""col2""> 2 </td><td class=""col3""> 3 </td></tr>
<tr class=""row2""><td class=""col1""> 4 </td><td class=""col2""> 5 </td><td class=""col3""> 6 </td></tr>")]
        [TestCase(@"{% assign foo = values | split: "","" %}.{{ foo[1] }}.", @"{""values"":""foo,bar,baz""}", @".bar.")]
        [TestCase(@"{% assign foo = values %}.{{ foo[0] }}.", @"{""values"":[""foo"",""bar"",""baz""]}", @".foo.")]
        [TestCase(@"{% assign foo = values %}.{{ foo[1] }}.", @"{""values"":[""foo"",""bar"",""baz""]}", @".bar.")]
        [TestCase(@"{% if var == nil %} true {% else %} false {% endif %}", @"{""var"":null}", @"true")]
        [TestCase(@"{% if var == null %} true {% else %} false {% endif %}", @"{""var"":null}", @"true")]
        [TestCase(@"{% if array == empty %} true {% else %} false {% endif %}", @"{""array"":[]}", @"true")]
        [TestCase(@"{% if var != nil %} true {% else %} false {% endif %}", @"{""var"":1}", @"true")]
        [TestCase(@"{% if var != null %} true {% else %} false {% endif %}", @"{""var"":1}", @"true")]
        [TestCase(@"{% if 'test' == 'test' %} true {% else %} false {% endif %}", @"{}", @"true")]
        [TestCase(@"{% if 0 < 1 %} true {% else %} false {% endif %}", @"{}", @"true")]
        [TestCase(@"{% if 1 > 0 %} true {% else %} false {% endif %}", @"{}", @"true")]
        [TestCase(@"{% if var == 'hello there!' %} true {% else %} false {% endif %}", @"{""var"":""hello there!""}", @"true")]
        [TestCase(@"{% if true != true %} true {% else %} false {% endif %}", @"{}", @"false")]
        [TestCase(@"{% if 'hello there!' == var %} true {% else %} false {% endif %}", @"{""var"":""hello there!""}", @"true")]
        [TestCase(@"{% if true == true %} true {% else %} false {% endif %}", @"{}", @"true")]
        [TestCase(@"{% if 0 > 0 %} true {% else %} false {% endif %}", @"{}", @"false")]
        [TestCase(@"{% if 'test' != 'test' %} true {% else %} false {% endif %}", @"{}", @"false")]
        [TestCase(@"{% if var == ""hello there!"" %} true {% else %} false {% endif %}", @"{""var"":""hello there!""}", @"true")]
        [TestCase(@"{% if ""hello there!"" == var %} true {% else %} false {% endif %}", @"{""var"":""hello there!""}", @"true")]
        [TestCase(@"{% if 0 <= 0 %} true {% else %} false {% endif %}", @"{}", @"true")]
        [TestCase(@"{% if null <= 0 %} true {% else %} false {% endif %}", @"{}", @"false")]
        [TestCase(@"{% if 0 <= null %} true {% else %} false {% endif %}", @"{}", @"false")]
        [TestCase(@"{% if array == empty %} true {% else %} false {% endif %}", @"{""array"":[1,2,3]}", @"false")]
        [TestCase(@"{% if 0 >= 0 %} true {% else %} false {% endif %}", @"{}", @"true")]
        [TestCase(@"{%increment port %}", @"{}", @"0")]
        [TestCase(@"{%decrement port %}", @"{""port"":10}", @"9")]
        //[TestCase(@"{% break %}", @"{""i"":1}", @"")]
        public void It_Should_Match_Ruby_Output(String input, String assigns, String expected) {

            // Arrange
            ITemplateContext ctx = new TemplateContext()
                .WithAllFilters()
                .WithFileSystem(new TestFileSystem());
            
            foreach (var tuple in DictionaryFactory.CreateStringMapFromJson(assigns))
            {
                ctx.Define(tuple.Item1, tuple.Item2);
            }

            
            var template = LiquidTemplate.Create(input);
            
            // Act
            String result = template.Render(ctx);
        
            // Assert
            Assert.That(result.Trim(), Is.EqualTo(expected));
        }

        
    }
}
