//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     Source: truthy.txt
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Liquid.Ruby\writetest.rb
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Liquid.NET.Constants;
using NUnit.Framework;

namespace Liquid.NET.Tests.Ruby
{
    [TestFixture]
    public class TruthyTests {

        [Test]
        [TestCase(@"{% assign myarray = ""1"" |split: "","" %}{% if myarray %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"TRUTHY")]
        [TestCase(@"{% if myarray %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"NOT TRUTHY")]
        [TestCase(@"{% if myundefined == empty %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"NOT TRUTHY")]
        [TestCase(@"{% if myundefined == blank %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"TRUTHY")]
        [TestCase(@"{% if nil == empty %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"NOT TRUTHY")]
        [TestCase(@"{% if "" "" == blank %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"TRUTHY")]
        [TestCase(@"{% if ""notblank"" == blank %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"NOT TRUTHY")]
        [TestCase(@"{% assign space = "" "" %}{% if space == blank %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"TRUTHY")]
        [TestCase(@"{% assign space = "" "" %}{% if space == empty %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"NOT TRUTHY")]
        [TestCase(@"{% if "" "".empty? %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"TRUTHY")]
        [TestCase(@"{% if "" "".blank? %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"TRUTHY")]
        [TestCase(@"{% assign myvar = 123 %}{% if myvar.empty? %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"NOT TRUTHY")]
        [TestCase(@"{% if myvar.empty? %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"NOT TRUTHY")]
        [TestCase(@"{% if myvar.blank? %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"NOT TRUTHY")]
        [TestCase(@"{% assign myvar = 123 %}{% if myvar == empty %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"NOT TRUTHY")]
        [TestCase(@"{% assign myarray = ""1,2"" |split: "","" %}{% if myarray == blank %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"NOT TRUTHY")]
        [TestCase(@"{% assign myarray = """" |split: "","" %}{% if myarray == blank %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"TRUTHY")]
        [TestCase(@"{% assign myarray = ""1,2"" |split: "","" %}{% if myarray == empty %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"NOT TRUTHY")]
        [TestCase(@"{% assign myarray = """" |split: "","" %}{% if myarray == empty %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"TRUTHY")]
        [TestCase(@"{% assign myarray = """" |split: "","" %}{% if myarray == present %}TRUTHY{% else %}NOT TRUTHY{% endif %}", @"", @"NOT TRUTHY")]
        public void It_Should_Match_Ruby_Output(String input, String assigns, String expected) {

            // Arrange
            ITemplateContext ctx = new TemplateContext().WithAllFilters();
            
            foreach (var tuple in DictionaryFactory.CreateStringMapFromJson(assigns))
            {
                ctx.DefineLocalVariable(tuple.Item1, tuple.Item2);
            }

            
            var template = LiquidTemplate.Create(input);
            
            // Act
            String result = template.Render(ctx);
        
            // Assert
            Assert.That(result.Trim(), Is.EqualTo(expected));
        }

        
    }
}
